services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: rag_it_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./services/qdrant/config.yaml:/qdrant/config/production.yaml
      - ./data/qdrant:/qdrant/storage
    networks:
      - rag_network

  ollama:
    image: ollama/ollama:latest
    restart: always
    container_name: rag_it_ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - rag_network

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: rag_it_backend
    ports:
      - "8000:8000"
    volumes:
      - ./services/backend/src:/app/src
      - ./data/uploads:/app/uploads
      - ./data/processing:/app/processing
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - EMBEDDING_SERVICE_URL=http://embeddings:8001
    depends_on:
      - qdrant
      - ollama
      - embeddings
    restart: always
    networks:
      - rag_network

  embeddings:
    build:
      context: ./services/embeddings
      dockerfile: Dockerfile
    container_name: rag_it_embeddings
    ports:
      - "8001:8001"
    environment:
      - EMBEDDING_MODEL=BAAI/bge-large-en-v1.5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge