services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: rag_it_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      # Config
      - ./config/qdrant.yaml:/qdrant/config/production.yaml
      # Data
      - ./data/qdrant:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    restart: always
    container_name: rag_it_ollama
    ports:
      - "11434:11434"
    volumes:
      # Data
      - ./data/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]