log_level: INFO

storage:
  storage_path: /qdrant/storage
  on_disk_payload: true
  
  performance:
    max_search_threads: 0  # 0 is Auto-Select. Can be negative to take total minus that or positive for fixed amount.
    optimizer_cpu_budget: 0  # Same thing here
  
  optimizers:
    deleted_threshold: 0.2
    vacuum_min_vector_number: 1000
    default_segment_number: 0 # must be equal to search threads, auto (0) does that
    max_segment_size_kb: null # auto set based on CPU
    indexing_threshold_kb: 20000  # IDK WHAT TO SET HERE AI SAID MAKES SENSE
    flush_interval_sec: 5
    max_optimization_threads: null

  hnsw_index:
    m: 16 # DEFAULT BUT MAYBE CHANGE? Number of edges per node in the index graph. Larger the value - more accurate the search, more space required.
    ef_construct: 100 # Amount of neighbours for index. Maybe change.
    full_scan_threshold_kb: 10000 # Minimal size threshold (in KiloBytes) below which full-scan is preferred over HNSW search.
    max_indexing_threads: 12
    on_disk: false  # Index kept in RAM

service:
  max_request_size_mb: 32
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
  max_workers: 0  # Auto-select
  enable_cors: true   # More info: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

cluster:
  enabled: false

telemetry_disabled: true

# For TLS encryption see Default Config
# https://github.com/qdrant/qdrant/blob/master/config/config.yaml
