services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports: ["11434:11434"]
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "/bin/sh", "-lc", "ollama list >/dev/null 2>&1"]
      interval: 10s
      timeout: 6s
      retries: 20
    gpus: all

  pull-mistral:
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ollama:/root/.ollama
    entrypoint: ["/bin/sh","-lc","ollama pull mistral"]

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports: ["3000:8080"]
    depends_on:
      - ollama
    environment:
      # Some builds expect BASE_URL, others API_BASE — set both.
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_API_BASE=http://ollama:11434
    volumes:
      - openwebui:/app/backend/data

volumes:
  ollama:
  openwebui:

